### ISSUE TITLE
Docker bind plugins

### ISSUE THREAD

**Issue by loewal** [0xAF/openwebrxplus-plugins#1]
Hi,

I am using your docker-version successfully. Thank you for that!
But...the plugins-instructions are somehow not succesful..
I use:
docker run -d --name owrxp     --device /dev/bus/usb --device=/dev/ttyUSB0    -p 8073:8073     -v owrxp-settings:/var/lib/openwebrx     -v owrxp-etc:/etc/openwebrx  -v /var/lib/docker/overlay2/cdf36e64851b23d0f028ac09559d0555566e4a25126ad47b9f8d0f531490d99b/merged/usr/lib/python3/dist-packages/htdocs/plugins   --restart unless-stopped     slechev/openwebrxplus

As you can see, I also added "--device=/dev/ttyUSB0" to get the codecserver up and running.
What am I doing wrong with the volume map and bind for the plugins?

Regards,
Loe

**Comment by 0xAF** [comment]
Hi.
You need the `--device=/dev/ttyUSB0` not for codecserver probably, but for your SDR device.  
This is most likely because of `--device /dev/bus/usb`.  
If you change the `--device /dev/bus/usb` with `-v /dev/bus/usb:/dev/bus/usb`, it will probably work for all sdr devices you have there. And you can remove the `--device=/dev/ttyUSB0` too.

As for the plugins, you need to bind-mount a folder, where your plugins will reside, and it will be mounted into the docker container.
The folder, which you're using is not correct. As I can see, you are trying to mount the real (on-host) folder, belonging to the docker internal filesystem, which is bad. You should not touch these folders. You will probably break your container or some files in it.
Try binding the folder in one of the following ways:  
1. `-v /path/to/your/owrx/plugins:/opt/openwebrx/htdocs/plugins` (which will use a folder from your host's file system)  
2. `-v owrx-plugins:/opt/openwebrx/htdocs/plugins` (which will use a volume, which you need to create before using this option... and you will need to find a way, how to put the plugins in the volume. If you're not experienced with docker, use the 1st option)

the first option is the easiest one.

Please report of your experience.

**Comment by loewal** [comment]
Hi, thanks for your quick reply!

1) -v /dev/bus/usb:/dev/bus/usb    had to restore this, because "-v /dev/bus/usb:/dev/bus/usb" didn't work.
2) I created a folder /opt/openwebrx/htdocs/plugins and put the folders map and receiver in there
    then add -v /opt/openwebrx/htdocs/plugins:/opt/openwebrx/htdocs/plugins
But I have a feeling, that the last line isn't correct, because it doesn't work. Or do I have to change something with chmod or chown?

Thanks

**Comment by loewal** [comment]
--device=/dev/ttyUSB0 and --device=/dev/ttyUSB0 of course...

**Comment by loewal** [comment]
Also tried -v plugins:/opt/openwebrx/htdocs/plugins
The volume is bound, but also no success....pity..

**Comment by loewal** [comment]
And at last. -v owrx-plugins:/opt/openwebrx/htdocs/plugins
Also not...
Sorry for the many tries and comments....

**Comment by loewal** [comment]
Didn't read well...
-v owrxp-plugins:/opt/openwebrx/htdocs/plugins  forgot the "p"..."owrxp"
but also :(

**Comment by 0xAF** [comment]
So, have you got it working in the end? I got confused by your comments.
BTW, you can edit your comments. It is better to edit the first comment instead of writing few of them.

If it's not working yet, please show me the command you're trying?

**Comment by loewal** [comment]
No, it's not working yet.
Codecserver and all digimodes also.

My command:
docker run -d --name owrxp-nightly --device /dev/bus/usb --device=/dev/ttyUSB0 -p 8073:8073 -v owrxp-settings:/var/lib/openwebrx -v owrxp-etc:/etc/openwebrx -v owrxp-plugins:/opt/openwebrx/htdocs/plugins --restart unless-stopped slechev/openwebrxplus-nightly

**Comment by loewal** [comment]
> So, have you got it working in the end? I got confused by your comments. BTW, you can edit your comments. It is better to edit the first comment instead of writing few of them.
> 
> If it's not working yet, please show me the command you're trying?

Sorry, last entry was not a comment...have to learn yet.

**Comment by loewal** [comment]
> So, have you got it working in the end? I got confused by your comments. BTW, you can edit your comments. It is better to **_edit the first comment_** instead of writing few of them.
> 
> If it's not working yet, please show me the command you're trying?

I will

**Comment by 0xAF** [comment]
ok, try this commands:
```sh
mkdir -p /etc/openwebrx/plugins/receiver
docker run -d --name owrxp-nightly --device /dev/bus/usb --device=/dev/ttyUSB0 -p 8073:8073 -v owrxp-settings:/var/lib/openwebrx -v owrxp-etc:/etc/openwebrx -v /etc/openwebrx/plugins:/opt/openwebrx/htdocs/plugins --restart unless-stopped slechev/openwebrxplus-nightly
```
then you can install your plugins in `/etc/openwebrx/plugins`

**Comment by loewal** [comment]
Thank you Stanislav!

It's working great!!
